name: Import from Vitaly Kurin's notes
on:
  push:
    branches: [ main ]
jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2-beta # use either @v2-beta or @master. Eventually there will be a @v2 tag.
        with:
          fetch-depth: 0
          
      - name: Check changes
        id: check-changes
        uses: rdietrick/did-files-change@v1.2
        with:
          pathspec: pairs.txt

      - name: Run
        if: ${{ steps.check-changes.outputs.changed }}
        run: |
          echo "Will run something"

      - uses: stefanzweifel/git-auto-commit-action@v4
